name: Performing Tests

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/perform-test.yml'
      - 'src/**'
      - 'tests/**'
      - 'pnpm-lock.yaml'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/perform-test.yml'
      - 'src/**'
      - 'tests/**'
      - 'pnpm-lock.yaml'

jobs:
  run-tester:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prettier-version: [v3.0, v3.1, v3.2, v3.3, v3.4, v3.5, v3.6, v3.7]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: testing-prettier-${{ matrix.prettier-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: Perform a test
        run: pnpm run test
